# Upstream servers to sync with
pool 0.pool.ntp.org iburst maxsources 2
pool 1.pool.ntp.org iburst maxsources 2
pool 2.pool.ntp.org iburst maxsources 2

# Allow NTP from ANYWHERE
allow all

# Handle spikes
clientloglimit 1048576
ratelimit interval -4 burst 16 leak 2

# Immediate sync on startup
makestep 1.0 3

# Accuracy tuning
driftfile /var/lib/chrony/drift
rtcsync


logdir /var/log/chrony
