services:
  dns:
    image: "powerdns/pdns-recursor-54:latest"
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
  ntp:
    image: "cturra/ntp:latest"
    restart: unless-stopped
    ports:
      - "123:123/udp"
    cap_add:
      - SYS_TIME
    volumes:
      - chrony-data:/var/lib/chrony
    environment:
      - TZ=UTC
      - NTP_SERVERS="time.cloudflare.com time1.google.com"
      - ENABLE_NTS=true
volumes:
  chrony-data:
